# Generated by Django 6.0.2 on 2026-02-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('overview', models.TextField(blank=True, help_text='Brief overview shown at the top of the editorial page.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.topic')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown-formatted editorial text.')),
                ('section_type', models.CharField(choices=[('explanation', 'Explanation'), ('code', 'Code'), ('summary', 'Summary')], default='explanation', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='concepts.concept')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20)),
                ('code', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_final_code', models.BooleanField(default=False, help_text='Whether this is the complete implementation code.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='concepts.conceptsection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
