# Generated by Django 6.0.2 on 2026-02-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viz_type', models.CharField(choices=[('array', 'Array'), ('linked_list', 'Linked List'), ('stack', 'Stack'), ('queue', 'Queue'), ('tree', 'Tree'), ('graph', 'Graph'), ('heap', 'Heap')], max_length=20)),
                ('default_input', models.JSONField(blank=True, default=dict, help_text='Default data for the visualization, e.g. {"array": [5,3,8,1]}')),
                ('action_options', models.JSONField(blank=True, default=list, help_text='Available actions, e.g. ["insert", "delete", "search"]')),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visualization', to='concepts.concept')),
            ],
        ),
        migrations.CreateModel(
            name='AnimationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(help_text='Action this step belongs to (e.g., "insert", "sort_step")', max_length=50)),
                ('keyframes', models.JSONField(default=list, help_text='Array of frame objects describing state transitions.')),
                ('code_highlight', models.TextField(blank=True, help_text='Comma-separated line numbers to highlight during this step.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_steps', to='visualizer.visualizationconfig')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
